name: build

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA:0:7})"
      - name: Telegram Notification
        uses: appleboy/telegram-action@0.0.7
        with:
          message: ${{ env.GITHUB_ACTOR }} just pushed commit a [${{ steps.vars.outputs.sha_short }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) to [${{ steps.vars.outputs.repo_name }}](https://github.com/${{ github.repository }})
          format: markdown
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
